services:
  postgres:
    image: 'postgres:latest'
    restart: unless-stopped
    environment:
      - 'POSTGRES_DB=movies_play_db'
      - 'POSTGRES_PASSWORD=movies.play'
      - 'POSTGRES_USER=fernando'
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: